Repository GadiGoodi/front, pull requests merged in 2024-11, with the labels that each got.

#1 ARVU-62 tailWindCSS 설치 및 초기설정
  thiscoding/app/globals.css
  thiscoding/package-lock.json
  thiscoding/package.json
  thiscoding/postcss.config.js
  thiscoding/tailwind.config.js
Labels: 💻 Client, ⚙ Setting

#2 ARVU-63 chore: eslint, prettier 설정
  thiscoding/.eslintrc.json
  thiscoding/.prettierrc.json
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: 💻 Client, ⚙ Setting

#3 ARVU-64 chore: husky 설치 및 설정
  thiscoding/.husky/pre-commit
  thiscoding/.husky/pre-push
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: 💻 Client, ⚙ Setting

#4 ARVU-65 chore: lint-staged 설정 추가
  thiscoding/.husky/pre-commit
  thiscoding/.husky/pre-push
  thiscoding/package.json
Labels: 💻 Client, ⚙ Setting

#5 ARVU-66 build: mui, autoprefixer install
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: 💻 Client, ⚙ Setting

#6 ARVU-67 chore: react-icons 설치
  package-lock.json
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: ⚙ Setting

#8 ARVU-31 feat: 상단바 생성
  thiscoding/app/(components)/common/Headers.tsx
Labels: ✨ Feature, 🎨 Html&css

#9 ARVU-69 build: husky 삭제 후 재설치/경로변경
  .husky/pre-commit
  .husky/pre-push
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: ⚙ Setting

#10 ARVU-70 Feat/codingrooms modal
  thiscoding/app/(components)/CodingroomsModal.tsx
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: ✨ Feature, 🎨 Html&css

#11 ARVU-71 style:globals.css 공통 설정 추가
  thiscoding/app/globals.css
Labels: 🎨 Html&css, ⚙ Setting

#13 ARVU-74 feat: 관리자 공지사항 관리 페이지 퍼블리싱
  thiscoding/app/(components)/admin/Report.tsx
  thiscoding/app/(components)/admin/ReportContent.tsx
  thiscoding/app/(components)/admin/notices/Notices.tsx
  thiscoding/app/(components)/admin/notices/NoticesContent.tsx
  thiscoding/app/admin/notices/layout.tsx
  thiscoding/app/admin/notices/page.tsx
Labels: 🎨 Html&css

#15 ARVU-76 feat:마이페이지 북마크한 QnA 페이지 퍼블리싱
  thiscoding/app/(components)/mypage/bookmark/BookMarkQnA.tsx
  thiscoding/app/(components)/mypage/bookmark/BookMarkQnAContent.tsx
  thiscoding/app/mypage/bookmark/layout.tsx
  thiscoding/app/mypage/bookmark/page.tsx
Labels: 🎨 Html&css

#16 ARVU-77 feat:고객센터 페이지 퍼블리싱
  thiscoding/app/(components)/admin/adminNotices/AdminNotices.tsx
  thiscoding/app/(components)/admin/adminNotices/AdminNoticesContent.tsx
  thiscoding/app/(components)/notices/Notices.tsx
  thiscoding/app/(components)/notices/NoticesContent.tsx
  thiscoding/app/admin/notices/page.tsx
  thiscoding/app/globals.css
  thiscoding/app/notices/layout.tsx
  thiscoding/app/notices/page.tsx
Labels: 🎨 Html&css

#17 ARVU-77 feat:공지사항 삭제 페이지 퍼블리싱
  thiscoding/app/(components)/notices/[notices_Id]/NoticesDetail.tsx
  thiscoding/app/notices/[notices_Id]/page.tsx
Labels: 🎨 Html&css

#18 ARVU-74 feat:관리자 공지사항 상세 페이지 퍼블리싱
  thiscoding/app/(components)/admin/notices/[adminNotice_Id]/AdminNoticesDetail.tsx
  thiscoding/app/admin/notices/[adminNotice_Id]/page.tsx
Labels: 🎨 Html&css

#20 ARVU-70 feat: 코드방 생성 모달 퍼블리싱 완성
  thiscoding/app/(components)/CodingroomsModal.tsx
  thiscoding/package-lock.json
Labels: ✨ Feature, 🎨 Html&css

#21 ARVU-81 feat:QnA게시판 페이지 퍼블리싱
  thiscoding/app/(components)/qna/QnA.tsx
  thiscoding/app/(components)/qna/QnAContent.tsx
  thiscoding/app/qna/layout.tsx
  thiscoding/app/qna/page.tsx
Labels: 🎨 Html&css

#22 ARVU-82 feat:QnA 상세페이지 및 답변 목록 퍼블리싱
  thiscoding/app/(components)/qna/[qna_Id]/QnADetail.tsx
  thiscoding/app/(components)/qna/[qna_Id]/QnADetailAnswer.tsx
  thiscoding/app/qna/[qna_Id]/page.tsx
Labels: 🎨 Html&css

#24 ARVU-85 feat: 마이페이지 초대된 코드방 조회 퍼블리싱
  thiscoding/app/(components)/Pagination.tsx
  thiscoding/app/(components)/mypage/invitations/InvitaionsContent.tsx
  thiscoding/app/(components)/mypage/invitations/Invitations.tsx
  thiscoding/app/mypage/invitations/layout.tsx
  thiscoding/app/mypage/invitations/page.tsx
Labels: 🎨 Html&css

#25 ARVU-28 feat: 메인페이지 생성
  thiscoding/app/page.tsx
  thiscoding/public/asset/banner.png
  thiscoding/public/asset/mainImg.png
Labels: 🎨 Html&css

#26 ARVU-28 feat: Top10 컴포넌트 생성
  thiscoding/app/(components)/Top10.tsx
Labels: 🎨 Html&css

#27 ARVU-28 chore: 헤더 프로필 기본 이미지 삽입
  thiscoding/app/(components)/common/Headers.tsx
  thiscoding/public/asset/defaultImage.png
Labels: 🎨 Html&css

#29 ARVU-28 feat: 로그인, 회원가입 모달 생성
  thiscoding/app/(components)/common/LogIn.tsx
  thiscoding/app/(components)/common/SignUp.tsx
Labels: 🎨 Html&css

#31 ARVU-86 feat:유저 신고 모달 퍼블리싱 구현
  thiscoding/app/(components)/common/UserReportModal.tsx
  thiscoding/app/(components)/qna/[qna_Id]/QnADetail.tsx
Labels: 🎨 Html&css

#33 ARVU-88 feat:QnA 답변 상세,댓글,답글 퍼블리싱
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Answer.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Comment.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Reply.tsx
  thiscoding/app/qna/[qna_Id]/[answer_Id]/page.tsx
Labels: 🎨 Html&css

#34 ARVU-30 feat: 채팅방 프로필 기능 구현, 채팅 수정
  thiscoding/app/(components)/chat/ChatList.tsx
  thiscoding/app/(components)/chat/ChatListContent.tsx
  thiscoding/app/(components)/chat/ChatRoom.tsx
  thiscoding/app/(components)/chat/FriendList.tsx
  thiscoding/app/(components)/chat/FriendListContent.tsx
  thiscoding/app/(components)/chat/Messenger.tsx
  thiscoding/app/(components)/chat/Profile.tsx
Labels: 🔨 Fix, 🎨 Html&css

#35 ARVU-89 feat: 코드방 에디터, 사이드 탭 퍼블리싱
  thiscoding/app/(components)/codingrooms/CodeEditor.tsx
  thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx
  thiscoding/app/codingrooms/layout.tsx
  thiscoding/app/codingrooms/page.tsx
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: ✨ Feature, 🎨 Html&css

#36 ARVU-30 feat: 채팅 나가기 버튼 퍼블리싱
  thiscoding/app/(components)/chat/ChatBtn.tsx
  thiscoding/app/(components)/chat/ChatListContent.tsx
  thiscoding/app/(components)/chat/Dropdown.tsx
  thiscoding/app/(components)/chat/FriendListContent.tsx
  thiscoding/app/(components)/chat/Profile.tsx
Labels: 🔨 Fix, 🎨 Html&css

#37 ARVU-88 feat:QnA 댓글,답글 작성 및 태그 퍼블리싱
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Answer.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Comment.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Reply.tsx
Labels: 🎨 Html&css

#38 ARVU-90 feat:QnA 작성 페이지 퍼블리싱
  thiscoding/app/(components)/qna/QnA.tsx
  thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx
  thiscoding/app/admin/notices/post-notices/page.tsx
  thiscoding/app/mypage/post-qna/layout.tsx
  thiscoding/app/mypage/post-qna/page.tsx
  thiscoding/app/qna/post-qna/layout.tsx
  thiscoding/app/qna/post-qna/page.tsx
Labels: 🎨 Html&css

#39 ARVU-21 Chore: 로그인, 회원가입 모달 소셜 이미지 png 삽입, 토글 기능 추가, 메인 slide 구현
  thiscoding/app/(components)/Top10.tsx
  thiscoding/app/(components)/common/SignUp.tsx
  thiscoding/app/page.tsx
  thiscoding/public/asset/googleIcon.png
  thiscoding/public/asset/kakaoIcon.png
  thiscoding/public/asset/naverIcon.png
Labels: 🎨 Html&css

#41 ARVU-89 fix: 코드방 좌측 탭 수정 및 상단 탭 추가
  thiscoding/app/(components)/codingrooms/CodeEditor.tsx
Labels: ✨ Feature, 🔨 Fix, 🎨 Html&css

#42 ARVU-21 build: 슬라이드 라이브러리 모듈 설치
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: 🎨 Html&css

#43 ARVU-28 fix:로그인,회원가입 모달 핸들러 수정
  thiscoding/app/page.tsx
Labels: 🔨 Fix, 🎨 Html&css

#44 ARVU-28 chore: 헤더에 주소 수정
  thiscoding/app/(components)/common/Headers.tsx
Labels: 🎨 Html&css

#47 ARVU-21 chore: 헤더에서 코딩방 생성 모달
  thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx
  thiscoding/app/(components)/common/Headers.tsx
Labels: 🎨 Html&css

#46 ARVU-91 feat:메인페이지 헤더 프로필 드롭다운 퍼블리싱
  thiscoding/app/(components)/common/Headers.tsx
Labels: 🎨 Html&css

#49 ARVU-21 chore: ellipsis 적용
  thiscoding/app/(components)/Top10.tsx
  thiscoding/app/globals.css
Labels: 🎨 Html&css

#50 ARVU-89 feat: 코드방 채팅탭, AI 채팅탭 퍼블리싱
  thiscoding/app/(components)/codingrooms/CodeEditor.tsx
Labels: ✨ Feature, 🎨 Html&css

#52 ARVU-50 feat: 코드방 에디터 컴파일 기능 구현
  thiscoding/app/(components)/codingrooms/CodeEditor.tsx
  thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx
Labels: ✨ Feature, 🔨 Fix

#53 ARVU-50 build: sockJS, stompJS 추가
  thiscoding/app/(apis)/webSocket.ts
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: ⚙ Setting
