Repository GadiGoodi/front, pull requests merged in 2024-12, with the labels that each got.

#54 ARVU-24 feat:관리자 공지사항 목록 조회 기능 구현
  thiscoding/app/(components)/admin/adminNotices/AdminNotices.tsx
  thiscoding/app/(models)/admin/adminNotices/AdminNoticesListDTO.ts
Labels: 💻 Client, ✨ Feature

#55 ARVU-24 feat:관리자 공지사항 작성 기능 구현
  thiscoding/app/(components)/admin/adminNotices/postNotices/AdminPostNotices.tsx
Labels: 💻 Client, ✨ Feature

#56 ARVU-24 feat:관리자 공지사항 삭제 기능 구현
  thiscoding/app/(components)/admin/adminNotices/AdminNoticesContent.tsx
Labels: 💻 Client, ✨ Feature

#57 ARVU-24 chore:관리자 공지사항 타입 작성
  thiscoding/app/(models)/admin/adminNotices/AdminNoticesDetailDTO.ts
  thiscoding/app/(models)/admin/adminNotices/AdminNoticesListDTO.ts
  thiscoding/app/(models)/users/User.ts
Labels: 💻 Client, ✨ Feature

#58 ARVU-24 feat:관리자 공지사항 작성,삭제,수정,조회 구현 및 api,hook 폴더로 분리
  thiscoding/app/(apis)/admin/adminApi.ts
  thiscoding/app/(components)/admin/adminNotices/AdminNotices.tsx
  thiscoding/app/(components)/admin/adminNotices/AdminNoticesContent.tsx
  thiscoding/app/(components)/notices/[notices_Id]/NoticesDetail.tsx
  thiscoding/app/(hooks)/admin/useAdmin.ts
Labels: 💻 Client, ✨ Feature

#59 ARVU-24 feat:관리자 CURD 기능 컴포넌트에 적용
  thiscoding/app/(components)/admin/adminNotices/postNotices/AdminPostNotices.tsx
  thiscoding/app/(components)/admin/notices/[adminNotice_Id]/AdminNoticesDetail.tsx
Labels: 💻 Client, ✨ Feature

#60 ARVU-25 feat:토스트ui를 사용한 QnA 작성 기능 구현
  thiscoding/app/(apis)/qna/qnaApi.ts
  thiscoding/app/(components)/qna/post-qna/ToastUi.tsx
  thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx
  thiscoding/app/(hooks)/qna/useQnA.ts
  thiscoding/package-lock.json
  thiscoding/package.json
Labels: 💻 Client, ✨ Feature

#61 ARVU-105 feat:QnA 전체조회 기능 구현
  thiscoding/app/(apis)/qna/qnaApi.ts
  thiscoding/app/(components)/qna/QnA.tsx
  thiscoding/app/(components)/qna/QnAContent.tsx
  thiscoding/app/(hooks)/qna/useQnA.ts
  thiscoding/app/(models)/qna/QnaListType.ts
Labels: 💻 Client, ✨ Feature

#63 ARVU-26 feat:QnA 댓글조회 기능구현 및 type 추가
  thiscoding/app/(apis)/qna/qnaApi.ts
  thiscoding/app/(components)/qna/[qna_Id]/QnADetail.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Comment.tsx
  thiscoding/app/(hooks)/qna/useQnA.ts
  thiscoding/app/(models)/qna/QnaCommentType.ts
Labels: 💻 Client, ✨ Feature

#64 ARVU-108 feat:마이페이지 작성Qna 조회 기능 구현
  thiscoding/app/(apis)/mypage/postQna/postQnaApi.ts
  thiscoding/app/(components)/mypage/qna/PostQnA.tsx
  thiscoding/app/(components)/mypage/qna/PostQnAContent.tsx
  thiscoding/app/(hooks)/mypage/post-qna/usePostQna.ts
  thiscoding/app/(models)/users/PostQnaType.ts
Labels: 💻 Client, ✨ Feature

#65 ARVU-34 chore: 메인 페이지 로그인 모달
  thiscoding/app/(apis)/userApi.ts
  thiscoding/app/(components)/common/LogIn.tsx
  thiscoding/app/page.tsx
Labels: 📬 API, 💻 Client, ✨ Feature

#66 ARVU-34 chore: 회원가입 모달
  thiscoding/app/(components)/common/Headers.tsx
  thiscoding/app/(components)/common/SignUp.tsx
  thiscoding/app/(hooks)/useSignUp.ts
  thiscoding/app/store/store.tsx
Labels: 💻 Client, ✨ Feature

#67 ARVU-37 chore: 마이페이지 기능 구현
  thiscoding/app/globals.css
  thiscoding/app/mypage/page.tsx
Labels: 💻 Client, ✨ Feature

#68 ARVU-36 chore: 비밀번호 찾기 모달
  thiscoding/app/(components)/common/EmailVerification.tsx
  thiscoding/app/(components)/common/FindPassword.tsx
Labels: 💻 Client, ✨ Feature

#69 ARVU-21 chore: 메인페이지 top10 수정
  thiscoding/app/(components)/Top10.tsx
Labels: 🎨 Html&css

#70 chore:소셜로그인 부분 import 삭제
  thiscoding/app/(components)/common/LogIn.tsx
Labels: 🐞 BugFix, 🔨 Fix

#71 fix:이메일 인증코드 body에서 param으로 변경.
  thiscoding/app/(hooks)/axiosConfig.ts
  thiscoding/app/(hooks)/useSignUp.ts
Labels: 🔨 Fix

#72 chore:axios를 axiosInstance 객체로 변경
  thiscoding/app/(apis)/admin/adminApi.ts
  thiscoding/app/(apis)/mypage/postQna/postQnaApi.ts
  thiscoding/app/(apis)/qna/qnaApi.ts
  thiscoding/app/(components)/mypage/qna/PostQnA.tsx
Labels: 🔨 Fix

#73 ARVU-31 chore: 헤더 부분에 코드방 안열리는 문제 수정
  thiscoding/app/(components)/common/Headers.tsx
Labels: 🔨 Fix

#74 refactor:공지사항,Qna useState,handler 리팩토링
  thiscoding/app/(apis)/qna/qnaApi.ts
  thiscoding/app/(components)/admin/adminNotices/postNotices/AdminPostNotices.tsx
  thiscoding/app/(components)/qna/post-qna/ToastUi.tsx
  thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx
  thiscoding/app/(hooks)/admin/useAdmin.ts
  thiscoding/app/(hooks)/qna/useQnA.ts
Labels: 💻 Client, 🔨 Fix

#75 fix:axios 인스턴스 withCredentials 설정 false로 변경
  thiscoding/app/(hooks)/axiosConfig.ts
Labels: 🐞 BugFix, 🔨 Fix

#76 ARVU-31 fix: headers 컴포넌트의 CodingroomsModal 닫히는 문제 수정
  thiscoding/app/(components)/common/Headers.tsx
Labels: 🔨 Fix

#77 ARVU-35 chore: 로그인할때 Enter 이벤트 추가
  thiscoding/app/(components)/common/LogIn.tsx
Labels: 💻 Client

#78 ARVU-35 chore: 헤더에서 로그아웃
  thiscoding/app/(components)/common/Headers.tsx
Labels: 🔨 Fix

#79 ARVU-50 feat: 웹 소켓 구독
  thiscoding/app/(apis)/codingrooms/codingroomsWebSocket.ts
  thiscoding/app/(apis)/webSocket.ts
Labels: ✨ Feature

#80 ARVU-50 feat: 코드 소켓 통신 및 저장
  thiscoding/app/(apis)/codingrooms/codingroomsApi.ts
  thiscoding/app/(apis)/codingrooms/codingroomsModalApi.ts
  thiscoding/app/(components)/codingrooms/CodingroomsModal.tsx
  thiscoding/app/(components)/codingrooms/[codingrooms_uuid]/CodeEditor.tsx
  thiscoding/app/(hooks)/codingrooms/useCodingrooms.ts
  thiscoding/app/(hooks)/codingrooms/useCodingroomsModal.ts
  thiscoding/app/(models)/codingrooms/CodingroomsDTO.ts
  thiscoding/app/codingrooms/[codingrooms_uuid]/page.tsx
  thiscoding/package.json
Labels: ✨ Feature

#81 ARVU-50 feat: 파일명 변경 메서드 추가
  thiscoding/app/(apis)/codingrooms/codingroomsApi.ts
  thiscoding/app/(components)/codingrooms/[codingrooms_uuid]/CodeEditor.tsx
  thiscoding/app/(hooks)/codingrooms/useCodingrooms.ts
  thiscoding/package-lock.json
Labels: ✨ Feature

#82 ARVU-89 feat: 마이페이지 참여 중인 코드방 퍼블리싱
  thiscoding/app/(apis)/codingrooms/codingroomsApi.ts
  thiscoding/app/(components)/codingrooms/[codingrooms_uuid]/CodeEditor.tsx
  thiscoding/app/(components)/mypage/participations/Participations.tsx
  thiscoding/app/(components)/mypage/participations/ParticipationsContent.tsx
  thiscoding/app/(hooks)/codingrooms/useCodingrooms.ts
  thiscoding/app/(hooks)/mypage/participations/useParticipations.ts
  thiscoding/app/(models)/codingrooms/CodingroomsDTO.ts
  thiscoding/app/mypage/participations/layout.tsx
  thiscoding/app/mypage/participations/page.tsx
Labels: 🎨 Html&css
