Repository GadiGoodi/front, pull requests merged in 2025-01, with the labels that each got.

#83 ARVU-50 fix: codingroomsModalApi POST 요청 URI 수정
  thiscoding/app/(apis)/codingrooms/codingroomsModalApi.ts
Labels: 🔨 Fix

#85 ARVU-34 feat: 회원가입 기능
  thiscoding/app/(components)/common/SignUp.tsx
  thiscoding/app/(hooks)/useSignUp.ts
  thiscoding/app/(hooks)/user/handleLogin.ts
  thiscoding/app/(models)/axiosWithAuth.ts
Labels: 💻 Client

#86 feat:ToastUi Viewer 사용 및 Comment useMutation으로 관리
  thiscoding/app/(apis)/admin/adminApi.ts
  thiscoding/app/(apis)/mypage/postQna/postQnaApi.ts
  thiscoding/app/(apis)/qna/qnaApi.ts
  thiscoding/app/(components)/admin/adminNotices/AdminNotices.tsx
  thiscoding/app/(components)/admin/adminNotices/AdminNoticesContent.tsx
  thiscoding/app/(components)/mypage/qna/PostQnA.tsx
  thiscoding/app/(components)/qna/QnA.tsx
  thiscoding/app/(components)/qna/QnAContent.tsx
  thiscoding/app/(components)/qna/[qna_Id]/QnADetail.tsx
  thiscoding/app/(components)/qna/[qna_Id]/QnADetailAnswer.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Comment.tsx
  thiscoding/app/(components)/qna/[qna_Id]/[answer_Id]/Reply.tsx
  thiscoding/app/(components)/qna/post-qna/ToastUi.tsx
  thiscoding/app/(components)/qna/post-qna/UserPostQnA.tsx
  thiscoding/app/(components)/qna/viewer.css
  thiscoding/app/(hooks)/mypage/post-qna/usePostQna.ts
  thiscoding/app/(hooks)/qna/useQnA.ts
  thiscoding/app/(models)/qna/QnaCommentType.ts
  thiscoding/app/(models)/qna/QnaListType.ts
Labels: 💻 Client, ✨ Feature, 🔨 Fix, 🎨 Html&css

#87 ARVU-12 refactor: 모달 구조 변경 및 설정
  thiscoding/app/(components)/common/ModalManager.tsx
  thiscoding/app/(components)/common/modals/FindPassword.tsx
  thiscoding/app/(components)/common/modals/LogIn.tsx
  thiscoding/app/(components)/common/modals/SignUp.tsx
Labels: 🔨 Fix

#88 ARVU-12 chore: axios에서 토큰 삭제하고, 로그인/ 회원가입 모달 표시
  thiscoding/app/(components)/common/Headers.tsx
  thiscoding/app/(models)/axiosWithAuth.ts
Labels: 🔨 Fix

#89 ARVU-12 refactor: 로그인/회원가입 모달과 훅, store 수정
  thiscoding/app/(apis)/userApi.ts
  thiscoding/app/(hooks)/useSignUp.ts
  thiscoding/app/(hooks)/user/useLogin.ts
  thiscoding/app/store/store.tsx
Labels: 🔨 Fix

#90 ARVU-12 chore: 메인 페이지 로그인 테스트
  thiscoding/app/page.tsx
Labels: 🔨 Fix

#91 ARVU-37 chore: 마이페이지 store 수정
  thiscoding/app/mypage/page.tsx
Labels: 🔨 Fix
